//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebflixApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESSE
    {
        public ADRESSE()
        {
            this.PERSONNEs = new HashSet<PERSONNE>();
        }
    
        public decimal IDADRESSE { get; set; }
        public decimal NUMCIVIQUE { get; set; }
        public string RUE { get; set; }
        public string VILLE { get; set; }
        public string PROVINCE { get; set; }
        public string CODEPOSTAL { get; set; }
    
        public virtual ICollection<PERSONNE> PERSONNEs { get; set; }
    }
}
