//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebflixApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTECREDIT
    {
        public CARTECREDIT()
        {
            this.CLIENTs = new HashSet<CLIENT>();
        }
    
        public decimal IDCARTECREDIT { get; set; }
        public string TYPE { get; set; }
        public string NUMERO { get; set; }
        public System.DateTime DATEEXPIRATION { get; set; }
        public decimal CVV { get; set; }
    
        public virtual ICollection<CLIENT> CLIENTs { get; set; }
    }
}
