//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebflixApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public CLIENT()
        {
            this.LOCATIONs = new HashSet<LOCATION>();
        }
    
        public decimal IDCLIENT { get; set; }
        public Nullable<decimal> IDPERSONNE { get; set; }
        public Nullable<decimal> IDCARTECREDIT { get; set; }
        public Nullable<decimal> IDFORFAIT { get; set; }
    
        public virtual CARTECREDIT CARTECREDIT { get; set; }
        public virtual ICollection<LOCATION> LOCATIONs { get; set; }
        public virtual FORFAIT FORFAIT { get; set; }
        public virtual PERSONNE PERSONNE { get; set; }
    }
}
