//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebflixApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM
    {
        public FILM()
        {
            this.ANNONCEs = new HashSet<ANNONCE>();
            this.COPIEs = new HashSet<COPIE>();
            this.FILMGENREs = new HashSet<FILMGENRE>();
            this.FILMPAYS = new HashSet<FILMPAY>();
            this.SCENARISTEs = new HashSet<SCENARISTE>();
            this.ROLEs = new HashSet<ROLE>();
        }
    
        public decimal IDFILM { get; set; }
        public string TITRE { get; set; }
        public System.DateTime DATEPARUTION { get; set; }
        public Nullable<decimal> DUREEFILM { get; set; }
        public string SCENARIO { get; set; }
        public string POSTER { get; set; }
        public decimal NBCOPIE { get; set; }
        public string LANGUEORIGINALE { get; set; }
        public Nullable<decimal> IDREALISATEUR { get; set; }
        public string CODE { get; set; }
    
        public virtual ICollection<ANNONCE> ANNONCEs { get; set; }
        public virtual ICollection<COPIE> COPIEs { get; set; }
        public virtual ICollection<FILMGENRE> FILMGENREs { get; set; }
        public virtual ICollection<FILMPAY> FILMPAYS { get; set; }
        public virtual ICollection<SCENARISTE> SCENARISTEs { get; set; }
        public virtual PERSONNESFILM PERSONNESFILM { get; set; }
        public virtual ICollection<ROLE> ROLEs { get; set; }
    }
}
