//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebflixApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENRE
    {
        public GENRE()
        {
            this.FILMGENREs = new HashSet<FILMGENRE>();
        }
    
        public decimal IDGENRE { get; set; }
        public string TITRE { get; set; }
    
        public virtual ICollection<FILMGENRE> FILMGENREs { get; set; }
    }
}
