//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebflixApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public decimal IDLOCATION { get; set; }
        public Nullable<System.DateTime> DATEDELOCATION { get; set; }
        public Nullable<System.DateTime> DATERETOUR { get; set; }
        public Nullable<decimal> IDCOPIE { get; set; }
        public Nullable<decimal> IDCLIENT { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual COPIE COPIE { get; set; }
    }
}
