//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebflixApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAY
    {
        public PAY()
        {
            this.FILMPAYS = new HashSet<FILMPAY>();
        }
    
        public decimal IDPAYS { get; set; }
        public string NOM { get; set; }
    
        public virtual ICollection<FILMPAY> FILMPAYS { get; set; }
    }
}
