//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebflixApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNESFILM
    {
        public PERSONNESFILM()
        {
            this.FILMs = new HashSet<FILM>();
            this.ROLEs = new HashSet<ROLE>();
        }
    
        public decimal IDPERSONNEFILM { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string BIO { get; set; }
        public string LIEUDENAISSANCE { get; set; }
        public string PHOTO { get; set; }
        public Nullable<System.DateTime> DATEDENAISSANCE { get; set; }
        public Nullable<decimal> CODE { get; set; }
    
        public virtual ICollection<FILM> FILMs { get; set; }
        public virtual ICollection<ROLE> ROLEs { get; set; }
    }
}
