//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebflixApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNE
    {
        public PERSONNE()
        {
            this.CLIENTs = new HashSet<CLIENT>();
            this.EMPLOYEs = new HashSet<EMPLOYE>();
        }
    
        public decimal IDPERSONNE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string COURRIEL { get; set; }
        public string TELEPHONE { get; set; }
        public Nullable<System.DateTime> DATEDENAISSANCE { get; set; }
        public string MOTDEPASSE { get; set; }
        public Nullable<decimal> IDADRESSE { get; set; }
    
        public virtual ADRESSE ADRESSE { get; set; }
        public virtual ICollection<CLIENT> CLIENTs { get; set; }
        public virtual ICollection<EMPLOYE> EMPLOYEs { get; set; }
    }
}
