//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebflixApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADRESSE> ADRESSEs { get; set; }
        public DbSet<ANNONCE> ANNONCEs { get; set; }
        public DbSet<CARTECREDIT> CARTECREDITs { get; set; }
        public DbSet<CLIENT> CLIENTs { get; set; }
        public DbSet<COPIE> COPIEs { get; set; }
        public DbSet<EMPLOYE> EMPLOYEs { get; set; }
        public DbSet<FILM> FILMs { get; set; }
        public DbSet<FILMGENRE> FILMGENREs { get; set; }
        public DbSet<FILMPAY> FILMPAYS { get; set; }
        public DbSet<FORFAIT> FORFAITs { get; set; }
        public DbSet<GENRE> GENREs { get; set; }
        public DbSet<LOCATION> LOCATIONs { get; set; }
        public DbSet<PAY> PAYS { get; set; }
        public DbSet<PERSONNE> PERSONNEs { get; set; }
        public DbSet<PERSONNESFILM> PERSONNESFILMs { get; set; }
        public DbSet<ROLE> ROLEs { get; set; }
        public DbSet<SCENARISTE> SCENARISTEs { get; set; }
    
        public virtual int ADDNEWPERSONNETEST(string nOM, string pRENOM, string tELEPHONE)
        {
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var pRENOMParameter = pRENOM != null ?
                new ObjectParameter("PRENOM", pRENOM) :
                new ObjectParameter("PRENOM", typeof(string));
    
            var tELEPHONEParameter = tELEPHONE != null ?
                new ObjectParameter("TELEPHONE", tELEPHONE) :
                new ObjectParameter("TELEPHONE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADDNEWPERSONNETEST", nOMParameter, pRENOMParameter, tELEPHONEParameter);
        }
    
        public virtual int INSCRIPTIONCLIENT(ObjectParameter iDCLIENT, Nullable<decimal> nUMCIVIQUE, string rUE, string vILLE, string pROVINCE, string cODEPOSTAL, string nOM, string pRENOM, string cOURRIEL, string tELEPHONE, Nullable<System.DateTime> dATEDENAISSANCE, string mOTDEPASSE, string tYPE, string nUMERO, Nullable<System.DateTime> dATEEXPIRATION, Nullable<decimal> cVV, string nOMFORFAIT)
        {
            var nUMCIVIQUEParameter = nUMCIVIQUE.HasValue ?
                new ObjectParameter("NUMCIVIQUE", nUMCIVIQUE) :
                new ObjectParameter("NUMCIVIQUE", typeof(decimal));
    
            var rUEParameter = rUE != null ?
                new ObjectParameter("RUE", rUE) :
                new ObjectParameter("RUE", typeof(string));
    
            var vILLEParameter = vILLE != null ?
                new ObjectParameter("VILLE", vILLE) :
                new ObjectParameter("VILLE", typeof(string));
    
            var pROVINCEParameter = pROVINCE != null ?
                new ObjectParameter("PROVINCE", pROVINCE) :
                new ObjectParameter("PROVINCE", typeof(string));
    
            var cODEPOSTALParameter = cODEPOSTAL != null ?
                new ObjectParameter("CODEPOSTAL", cODEPOSTAL) :
                new ObjectParameter("CODEPOSTAL", typeof(string));
    
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var pRENOMParameter = pRENOM != null ?
                new ObjectParameter("PRENOM", pRENOM) :
                new ObjectParameter("PRENOM", typeof(string));
    
            var cOURRIELParameter = cOURRIEL != null ?
                new ObjectParameter("COURRIEL", cOURRIEL) :
                new ObjectParameter("COURRIEL", typeof(string));
    
            var tELEPHONEParameter = tELEPHONE != null ?
                new ObjectParameter("TELEPHONE", tELEPHONE) :
                new ObjectParameter("TELEPHONE", typeof(string));
    
            var dATEDENAISSANCEParameter = dATEDENAISSANCE.HasValue ?
                new ObjectParameter("DATEDENAISSANCE", dATEDENAISSANCE) :
                new ObjectParameter("DATEDENAISSANCE", typeof(System.DateTime));
    
            var mOTDEPASSEParameter = mOTDEPASSE != null ?
                new ObjectParameter("MOTDEPASSE", mOTDEPASSE) :
                new ObjectParameter("MOTDEPASSE", typeof(string));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            var nUMEROParameter = nUMERO != null ?
                new ObjectParameter("NUMERO", nUMERO) :
                new ObjectParameter("NUMERO", typeof(string));
    
            var dATEEXPIRATIONParameter = dATEEXPIRATION.HasValue ?
                new ObjectParameter("DATEEXPIRATION", dATEEXPIRATION) :
                new ObjectParameter("DATEEXPIRATION", typeof(System.DateTime));
    
            var cVVParameter = cVV.HasValue ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(decimal));
    
            var nOMFORFAITParameter = nOMFORFAIT != null ?
                new ObjectParameter("NOMFORFAIT", nOMFORFAIT) :
                new ObjectParameter("NOMFORFAIT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSCRIPTIONCLIENT", iDCLIENT, nUMCIVIQUEParameter, rUEParameter, vILLEParameter, pROVINCEParameter, cODEPOSTALParameter, nOMParameter, pRENOMParameter, cOURRIELParameter, tELEPHONEParameter, dATEDENAISSANCEParameter, mOTDEPASSEParameter, tYPEParameter, nUMEROParameter, dATEEXPIRATIONParameter, cVVParameter, nOMFORFAITParameter);
        }
    
        public virtual int INSERTADRESS(ObjectParameter iD, Nullable<decimal> nUMCIVIQUE, string rUE, string vILLE, string pROVINCE, string cODEPOSTAL)
        {
            var nUMCIVIQUEParameter = nUMCIVIQUE.HasValue ?
                new ObjectParameter("NUMCIVIQUE", nUMCIVIQUE) :
                new ObjectParameter("NUMCIVIQUE", typeof(decimal));
    
            var rUEParameter = rUE != null ?
                new ObjectParameter("RUE", rUE) :
                new ObjectParameter("RUE", typeof(string));
    
            var vILLEParameter = vILLE != null ?
                new ObjectParameter("VILLE", vILLE) :
                new ObjectParameter("VILLE", typeof(string));
    
            var pROVINCEParameter = pROVINCE != null ?
                new ObjectParameter("PROVINCE", pROVINCE) :
                new ObjectParameter("PROVINCE", typeof(string));
    
            var cODEPOSTALParameter = cODEPOSTAL != null ?
                new ObjectParameter("CODEPOSTAL", cODEPOSTAL) :
                new ObjectParameter("CODEPOSTAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTADRESS", iD, nUMCIVIQUEParameter, rUEParameter, vILLEParameter, pROVINCEParameter, cODEPOSTALParameter);
        }
    
        public virtual int INSERTANNONCE(string lIEN, Nullable<decimal> iDFILM)
        {
            var lIENParameter = lIEN != null ?
                new ObjectParameter("LIEN", lIEN) :
                new ObjectParameter("LIEN", typeof(string));
    
            var iDFILMParameter = iDFILM.HasValue ?
                new ObjectParameter("IDFILM", iDFILM) :
                new ObjectParameter("IDFILM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTANNONCE", lIENParameter, iDFILMParameter);
        }
    
        public virtual int INSERTCARTECREDIT(ObjectParameter iD, string tYPE, string nUMERO, Nullable<System.DateTime> dATEEXPIRATION, Nullable<decimal> cVV)
        {
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            var nUMEROParameter = nUMERO != null ?
                new ObjectParameter("NUMERO", nUMERO) :
                new ObjectParameter("NUMERO", typeof(string));
    
            var dATEEXPIRATIONParameter = dATEEXPIRATION.HasValue ?
                new ObjectParameter("DATEEXPIRATION", dATEEXPIRATION) :
                new ObjectParameter("DATEEXPIRATION", typeof(System.DateTime));
    
            var cVVParameter = cVV.HasValue ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTCARTECREDIT", iD, tYPEParameter, nUMEROParameter, dATEEXPIRATIONParameter, cVVParameter);
        }
    
        public virtual int INSERTCLIENT(ObjectParameter iD, Nullable<decimal> iDPERSONNE, Nullable<decimal> iDCARTECREDIT, Nullable<decimal> iDFORFAIT)
        {
            var iDPERSONNEParameter = iDPERSONNE.HasValue ?
                new ObjectParameter("IDPERSONNE", iDPERSONNE) :
                new ObjectParameter("IDPERSONNE", typeof(decimal));
    
            var iDCARTECREDITParameter = iDCARTECREDIT.HasValue ?
                new ObjectParameter("IDCARTECREDIT", iDCARTECREDIT) :
                new ObjectParameter("IDCARTECREDIT", typeof(decimal));
    
            var iDFORFAITParameter = iDFORFAIT.HasValue ?
                new ObjectParameter("IDFORFAIT", iDFORFAIT) :
                new ObjectParameter("IDFORFAIT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTCLIENT", iD, iDPERSONNEParameter, iDCARTECREDITParameter, iDFORFAITParameter);
        }
    
        public virtual int INSERTCOPIE(ObjectParameter iD, Nullable<decimal> dISPONIBLE, Nullable<decimal> iDFILM)
        {
            var dISPONIBLEParameter = dISPONIBLE.HasValue ?
                new ObjectParameter("DISPONIBLE", dISPONIBLE) :
                new ObjectParameter("DISPONIBLE", typeof(decimal));
    
            var iDFILMParameter = iDFILM.HasValue ?
                new ObjectParameter("IDFILM", iDFILM) :
                new ObjectParameter("IDFILM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTCOPIE", iD, dISPONIBLEParameter, iDFILMParameter);
        }
    
        public virtual int INSERTEMPLOYE(ObjectParameter iD, Nullable<decimal> mATRICULE, Nullable<decimal> iDPERSONNE)
        {
            var mATRICULEParameter = mATRICULE.HasValue ?
                new ObjectParameter("MATRICULE", mATRICULE) :
                new ObjectParameter("MATRICULE", typeof(decimal));
    
            var iDPERSONNEParameter = iDPERSONNE.HasValue ?
                new ObjectParameter("IDPERSONNE", iDPERSONNE) :
                new ObjectParameter("IDPERSONNE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTEMPLOYE", iD, mATRICULEParameter, iDPERSONNEParameter);
        }
    
        public virtual int INSERTFILM(ObjectParameter iD, string tITRE, Nullable<System.DateTime> dATEPARUTION, Nullable<decimal> dUREEFILM, string sCENARIO, string pOSTER, Nullable<decimal> nBCOPIE, string lANGUEORIGINALE, Nullable<decimal> iDREALISATEUR, string cODE)
        {
            var tITREParameter = tITRE != null ?
                new ObjectParameter("TITRE", tITRE) :
                new ObjectParameter("TITRE", typeof(string));
    
            var dATEPARUTIONParameter = dATEPARUTION.HasValue ?
                new ObjectParameter("DATEPARUTION", dATEPARUTION) :
                new ObjectParameter("DATEPARUTION", typeof(System.DateTime));
    
            var dUREEFILMParameter = dUREEFILM.HasValue ?
                new ObjectParameter("DUREEFILM", dUREEFILM) :
                new ObjectParameter("DUREEFILM", typeof(decimal));
    
            var sCENARIOParameter = sCENARIO != null ?
                new ObjectParameter("SCENARIO", sCENARIO) :
                new ObjectParameter("SCENARIO", typeof(string));
    
            var pOSTERParameter = pOSTER != null ?
                new ObjectParameter("POSTER", pOSTER) :
                new ObjectParameter("POSTER", typeof(string));
    
            var nBCOPIEParameter = nBCOPIE.HasValue ?
                new ObjectParameter("NBCOPIE", nBCOPIE) :
                new ObjectParameter("NBCOPIE", typeof(decimal));
    
            var lANGUEORIGINALEParameter = lANGUEORIGINALE != null ?
                new ObjectParameter("LANGUEORIGINALE", lANGUEORIGINALE) :
                new ObjectParameter("LANGUEORIGINALE", typeof(string));
    
            var iDREALISATEURParameter = iDREALISATEUR.HasValue ?
                new ObjectParameter("IDREALISATEUR", iDREALISATEUR) :
                new ObjectParameter("IDREALISATEUR", typeof(decimal));
    
            var cODEParameter = cODE != null ?
                new ObjectParameter("CODE", cODE) :
                new ObjectParameter("CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTFILM", iD, tITREParameter, dATEPARUTIONParameter, dUREEFILMParameter, sCENARIOParameter, pOSTERParameter, nBCOPIEParameter, lANGUEORIGINALEParameter, iDREALISATEURParameter, cODEParameter);
        }
    
        public virtual int INSERTFILMGENRE(Nullable<decimal> iDFILM, Nullable<decimal> iDGENRE)
        {
            var iDFILMParameter = iDFILM.HasValue ?
                new ObjectParameter("IDFILM", iDFILM) :
                new ObjectParameter("IDFILM", typeof(decimal));
    
            var iDGENREParameter = iDGENRE.HasValue ?
                new ObjectParameter("IDGENRE", iDGENRE) :
                new ObjectParameter("IDGENRE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTFILMGENRE", iDFILMParameter, iDGENREParameter);
        }
    
        public virtual int INSERTFILMPAYS(Nullable<decimal> iDPAYS, Nullable<decimal> iDFILM)
        {
            var iDPAYSParameter = iDPAYS.HasValue ?
                new ObjectParameter("IDPAYS", iDPAYS) :
                new ObjectParameter("IDPAYS", typeof(decimal));
    
            var iDFILMParameter = iDFILM.HasValue ?
                new ObjectParameter("IDFILM", iDFILM) :
                new ObjectParameter("IDFILM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTFILMPAYS", iDPAYSParameter, iDFILMParameter);
        }
    
        public virtual int INSERTFORFAIT(ObjectParameter iD, string nAME, Nullable<decimal> pRIX, Nullable<decimal> lOCATIONSMAX, Nullable<decimal> dUREEMAX)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var pRIXParameter = pRIX.HasValue ?
                new ObjectParameter("PRIX", pRIX) :
                new ObjectParameter("PRIX", typeof(decimal));
    
            var lOCATIONSMAXParameter = lOCATIONSMAX.HasValue ?
                new ObjectParameter("LOCATIONSMAX", lOCATIONSMAX) :
                new ObjectParameter("LOCATIONSMAX", typeof(decimal));
    
            var dUREEMAXParameter = dUREEMAX.HasValue ?
                new ObjectParameter("DUREEMAX", dUREEMAX) :
                new ObjectParameter("DUREEMAX", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTFORFAIT", iD, nAMEParameter, pRIXParameter, lOCATIONSMAXParameter, dUREEMAXParameter);
        }
    
        public virtual int INSERTGENRE(ObjectParameter iD, string nEWTITRE)
        {
            var nEWTITREParameter = nEWTITRE != null ?
                new ObjectParameter("NEWTITRE", nEWTITRE) :
                new ObjectParameter("NEWTITRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTGENRE", iD, nEWTITREParameter);
        }
    
        public virtual int INSERTLOCATION(ObjectParameter iD, Nullable<System.DateTime> dATEDELOCATION, Nullable<System.DateTime> dATERETOUR, Nullable<decimal> iDCOPIE, Nullable<decimal> iDCLIENT)
        {
            var dATEDELOCATIONParameter = dATEDELOCATION.HasValue ?
                new ObjectParameter("DATEDELOCATION", dATEDELOCATION) :
                new ObjectParameter("DATEDELOCATION", typeof(System.DateTime));
    
            var dATERETOURParameter = dATERETOUR.HasValue ?
                new ObjectParameter("DATERETOUR", dATERETOUR) :
                new ObjectParameter("DATERETOUR", typeof(System.DateTime));
    
            var iDCOPIEParameter = iDCOPIE.HasValue ?
                new ObjectParameter("IDCOPIE", iDCOPIE) :
                new ObjectParameter("IDCOPIE", typeof(decimal));
    
            var iDCLIENTParameter = iDCLIENT.HasValue ?
                new ObjectParameter("IDCLIENT", iDCLIENT) :
                new ObjectParameter("IDCLIENT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTLOCATION", iD, dATEDELOCATIONParameter, dATERETOURParameter, iDCOPIEParameter, iDCLIENTParameter);
        }
    
        public virtual int INSERTPAYS(ObjectParameter iD, string nAME)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTPAYS", iD, nAMEParameter);
        }
    
        public virtual int INSERTPERSONNE(ObjectParameter iD, string nOM, string pRENOM, string cOURRIEL, string tELEPHONE, Nullable<System.DateTime> dATEDENAISSANCE, string mOTDEPASSE, Nullable<decimal> aDRESSE)
        {
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var pRENOMParameter = pRENOM != null ?
                new ObjectParameter("PRENOM", pRENOM) :
                new ObjectParameter("PRENOM", typeof(string));
    
            var cOURRIELParameter = cOURRIEL != null ?
                new ObjectParameter("COURRIEL", cOURRIEL) :
                new ObjectParameter("COURRIEL", typeof(string));
    
            var tELEPHONEParameter = tELEPHONE != null ?
                new ObjectParameter("TELEPHONE", tELEPHONE) :
                new ObjectParameter("TELEPHONE", typeof(string));
    
            var dATEDENAISSANCEParameter = dATEDENAISSANCE.HasValue ?
                new ObjectParameter("DATEDENAISSANCE", dATEDENAISSANCE) :
                new ObjectParameter("DATEDENAISSANCE", typeof(System.DateTime));
    
            var mOTDEPASSEParameter = mOTDEPASSE != null ?
                new ObjectParameter("MOTDEPASSE", mOTDEPASSE) :
                new ObjectParameter("MOTDEPASSE", typeof(string));
    
            var aDRESSEParameter = aDRESSE.HasValue ?
                new ObjectParameter("ADRESSE", aDRESSE) :
                new ObjectParameter("ADRESSE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTPERSONNE", iD, nOMParameter, pRENOMParameter, cOURRIELParameter, tELEPHONEParameter, dATEDENAISSANCEParameter, mOTDEPASSEParameter, aDRESSEParameter);
        }
    
        public virtual int INSERTPERSONNESFILM(Nullable<decimal> cODE, string nOM, string pRENOM, string bIO, string lIEUDENAISSANCE, string pHOTO, Nullable<System.DateTime> dATEDENAISSANCE)
        {
            var cODEParameter = cODE.HasValue ?
                new ObjectParameter("CODE", cODE) :
                new ObjectParameter("CODE", typeof(decimal));
    
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var pRENOMParameter = pRENOM != null ?
                new ObjectParameter("PRENOM", pRENOM) :
                new ObjectParameter("PRENOM", typeof(string));
    
            var bIOParameter = bIO != null ?
                new ObjectParameter("BIO", bIO) :
                new ObjectParameter("BIO", typeof(string));
    
            var lIEUDENAISSANCEParameter = lIEUDENAISSANCE != null ?
                new ObjectParameter("LIEUDENAISSANCE", lIEUDENAISSANCE) :
                new ObjectParameter("LIEUDENAISSANCE", typeof(string));
    
            var pHOTOParameter = pHOTO != null ?
                new ObjectParameter("PHOTO", pHOTO) :
                new ObjectParameter("PHOTO", typeof(string));
    
            var dATEDENAISSANCEParameter = dATEDENAISSANCE.HasValue ?
                new ObjectParameter("DATEDENAISSANCE", dATEDENAISSANCE) :
                new ObjectParameter("DATEDENAISSANCE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTPERSONNESFILM", cODEParameter, nOMParameter, pRENOMParameter, bIOParameter, lIEUDENAISSANCEParameter, pHOTOParameter, dATEDENAISSANCEParameter);
        }
    
        public virtual int INSERTROLE(string pERSONNAGE, Nullable<decimal> iDACTEUR, Nullable<decimal> iDFILM)
        {
            var pERSONNAGEParameter = pERSONNAGE != null ?
                new ObjectParameter("PERSONNAGE", pERSONNAGE) :
                new ObjectParameter("PERSONNAGE", typeof(string));
    
            var iDACTEURParameter = iDACTEUR.HasValue ?
                new ObjectParameter("IDACTEUR", iDACTEUR) :
                new ObjectParameter("IDACTEUR", typeof(decimal));
    
            var iDFILMParameter = iDFILM.HasValue ?
                new ObjectParameter("IDFILM", iDFILM) :
                new ObjectParameter("IDFILM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTROLE", pERSONNAGEParameter, iDACTEURParameter, iDFILMParameter);
        }
    
        public virtual int INSERTSCENARISTE(string nOM, Nullable<decimal> iDFILM)
        {
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var iDFILMParameter = iDFILM.HasValue ?
                new ObjectParameter("IDFILM", iDFILM) :
                new ObjectParameter("IDFILM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTSCENARISTE", nOMParameter, iDFILMParameter);
        }
    
        public virtual int LOUERFILM(ObjectParameter iDLOCATION, Nullable<decimal> iDCLIENT, Nullable<decimal> iDFILMS)
        {
            var iDCLIENTParameter = iDCLIENT.HasValue ?
                new ObjectParameter("IDCLIENT", iDCLIENT) :
                new ObjectParameter("IDCLIENT", typeof(decimal));
    
            var iDFILMSParameter = iDFILMS.HasValue ?
                new ObjectParameter("IDFILMS", iDFILMS) :
                new ObjectParameter("IDFILMS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOUERFILM", iDLOCATION, iDCLIENTParameter, iDFILMSParameter);
        }
    
        public virtual int RECHERCHEDATEPARUTION(Nullable<System.DateTime> mIN, Nullable<System.DateTime> mAX)
        {
            var mINParameter = mIN.HasValue ?
                new ObjectParameter("MIN", mIN) :
                new ObjectParameter("MIN", typeof(System.DateTime));
    
            var mAXParameter = mAX.HasValue ?
                new ObjectParameter("MAX", mAX) :
                new ObjectParameter("MAX", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RECHERCHEDATEPARUTION", mINParameter, mAXParameter);
        }
    
        public virtual int RECHERCHEFILMACTEUR(string nOMS)
        {
            var nOMSParameter = nOMS != null ?
                new ObjectParameter("NOMS", nOMS) :
                new ObjectParameter("NOMS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RECHERCHEFILMACTEUR", nOMSParameter);
        }
    
        public virtual int RECHERCHEFILMGENRE(string gENRES)
        {
            var gENRESParameter = gENRES != null ?
                new ObjectParameter("GENRES", gENRES) :
                new ObjectParameter("GENRES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RECHERCHEFILMGENRE", gENRESParameter);
        }
    
        public virtual int RECHERCHEFILMLANGUE(string lANGUE)
        {
            var lANGUEParameter = lANGUE != null ?
                new ObjectParameter("LANGUE", lANGUE) :
                new ObjectParameter("LANGUE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RECHERCHEFILMLANGUE", lANGUEParameter);
        }
    
        public virtual int RECHERCHEFILMPAYS(string pAYSRECHERCHER)
        {
            var pAYSRECHERCHERParameter = pAYSRECHERCHER != null ?
                new ObjectParameter("PAYSRECHERCHER", pAYSRECHERCHER) :
                new ObjectParameter("PAYSRECHERCHER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RECHERCHEFILMPAYS", pAYSRECHERCHERParameter);
        }
    
        public virtual int RECHERCHEFILMREALISATEUR(string nOMS)
        {
            var nOMSParameter = nOMS != null ?
                new ObjectParameter("NOMS", nOMS) :
                new ObjectParameter("NOMS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RECHERCHEFILMREALISATEUR", nOMSParameter);
        }
    
        public virtual int RECHERCHEFILMTITRE(string tITRES)
        {
            var tITRESParameter = tITRES != null ?
                new ObjectParameter("TITRES", tITRES) :
                new ObjectParameter("TITRES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RECHERCHEFILMTITRE", tITRESParameter);
        }
    
        public virtual int RETOURNERFILM(Nullable<decimal> iDLOCATIONS)
        {
            var iDLOCATIONSParameter = iDLOCATIONS.HasValue ?
                new ObjectParameter("IDLOCATIONS", iDLOCATIONS) :
                new ObjectParameter("IDLOCATIONS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RETOURNERFILM", iDLOCATIONSParameter);
        }
    
        public virtual int RETOURNERIDCLIENT(ObjectParameter iDCLIENT, string cOURRIELS, string mOTDEPASSES)
        {
            var cOURRIELSParameter = cOURRIELS != null ?
                new ObjectParameter("COURRIELS", cOURRIELS) :
                new ObjectParameter("COURRIELS", typeof(string));
    
            var mOTDEPASSESParameter = mOTDEPASSES != null ?
                new ObjectParameter("MOTDEPASSES", mOTDEPASSES) :
                new ObjectParameter("MOTDEPASSES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RETOURNERIDCLIENT", iDCLIENT, cOURRIELSParameter, mOTDEPASSESParameter);
        }
    }
}
